services:
  - type: web  # Defines a single web service
    name: kid-snack-app  # Name for your application
    env: python  # Python environment for Flask backend
    plan: free  # Render plan (choose according to your needs)
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt 
      # Install Node.js dependencies and build the React app
      cd frontend && npm install && npm run build 
      cd ..
      mkdir -p static
      # Copy the React build output to the Flask static folder
      cp -r frontend/build/* static/
    startCommand: gunicorn app:app
    envVars:  # Environment variables needed for the application
      - key: OPENAI_API_KEY
        value: sk-proj-3CDGAsY4Lg9LAMifw3eqEY24IZ7DdLhJsY4aRONDMapF7yOcTSsVUyLKCL3NUH7EdX0Avv31HQT3BlbkFJ  # Replace with your OpenAI API Key
      - key: OPENAI_ORGANIZATION
        value: org-yy3ASFoJmuSNux38QrZwhoGq
      - key: OPENAI_PROJECT
        value: proj_JHq0amAdO76lKTG66gwqBKvY
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: 'sqlite:///children.db'
      - key: REACT_APP_API_BASE_URL
        value: "https://kid-snack-app.onrender.com"  # Replace with your backend URL

    autoDeploy: true  # Enable automatic deployment on changes
    region: oregon  # Choose your preferred region
    healthCheckPath: /api/children  # Update this to the appropriate health check path