from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5f32c767ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exclusions', sa.String(length=500), nullable=True),
    sa.Column('dummy_column', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('child_snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('snack', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_snack')
    op.drop_table('child')
    # ### end Alembic commands ###